# libcxxabi-ignore-libstdcxx.cmake (patched)
set(LLVM_LIBSTDCXX_MINIMUM_VERSION "7.4" CACHE STRING "" FORCE)
set(LLVM_LIBSTDCXX_OK TRUE CACHE BOOL "" FORCE)
set(LLVM_LIBSTDCXX_CHECK OFF CACHE BOOL "" FORCE)
