# libcxxabi-ignore-libstdcxx.cmake (patched)
set(LLVM_LIBSTDCXX_MINIMUM_VERSION "7.4" CACHE STRING "" FORCE)
set(LLVM_LIBSTDCXX_OK FALSE CACHE BOOL "" FORCE)
set(LLVM_LIBSTDCXX_CHECK OFF CACHE BOOL "" FORCE)
#
# also ignore GCC (patched)
set(LIBCXXABI_HAS_GCC_LIB OFF CACHE BOOL "" FORCE)
set(LIBCXXABI_HAS_GCC_S_LIB OFF CACHE BOOL "" FORCE)
